project:
  hello: i am test

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.105:3306/mall?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: wang123
    hikari:
      connectionTimeout: 5000
      maximumPoolSize: 30
      maxLifeTime: 28500000